// <auto-generated />
namespace QuickBook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modifyadd_item : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifyadd_item));
        
        string IMigrationMetadata.Id
        {
            get { return "201805010900426_modify-add_item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
